# -*- coding: utf-8 -*-
"""Quiz200.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ED2y_Ck92yqzK3qTABAkswyh2JzDRglB
"""

from IPython import get_ipython
from IPython.display import display
import random

malware_level2_questions = [
    {
        "id": "malware_l2_q1",
        "field": "Malware Analysis",
        "question": "Which API call is most commonly monitored for malware process injection?",
        "options": ["CreateProcess", "WriteProcessMemory", "LoadLibrary", "ReadProcessMemory"],
        "correct_answer": "WriteProcessMemory",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q2",
        "field": "Malware Analysis",
        "question": "What is the purpose of a packer in malware distribution?",
        "options": ["To debug code", "To analyze traffic", "To obfuscate binaries", "To patch vulnerabilities"],
        "correct_answer": "To obfuscate binaries",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q3",
        "field": "Malware Analysis",
        "question": "Which Windows Registry key is often used for persistence by malware?",
        "options": ["HKCU\\Software\\Classes", "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run", "HKCR\\AppID", "HKU\\DEFAULT"],
        "correct_answer": "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q4",
        "field": "Malware Analysis",
        "question": "How does a polymorphic virus differ from a regular one?",
        "options": ["It changes its signature", "It targets hardware", "It can’t be decompiled", "It encrypts files"],
        "correct_answer": "It changes its signature",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q5",
        "field": "Malware Analysis",
        "question": "Which disassembler is most popular in advanced malware reverse engineering?",
        "options": ["OllyDbg", "Ghidra", "Burp Suite", "Nmap"],
        "correct_answer": "Ghidra",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q6",
        "field": "Malware Analysis",
        "question": "What type of malware is often embedded inside Microsoft Office macros?",
        "options": ["Worm", "Trojan", "Dropper", "Macro virus"],
        "correct_answer": "Macro virus",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q7",
        "field": "Malware Analysis",
        "question": "What is a common file extension used by ransomware?",
        "options": [".exe", ".zip", ".enc", ".dll"],
        "correct_answer": ".enc",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q8",
        "field": "Malware Analysis",
        "question": "Which tool is used to analyze dynamic behavior of malware?",
        "options": ["IDA Pro", "Wireshark", "Cuckoo Sandbox", "Volatility"],
        "correct_answer": "Cuckoo Sandbox",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q9",
        "field": "Malware Analysis",
        "question": "What is DLL sideloading in malware techniques?",
        "options": ["Loading a library remotely", "Hijacking a trusted process", "Forcing execution of fake DLLs", "Unloading system libraries"],
        "correct_answer": "Forcing execution of fake DLLs",
        "language_required": "N/A"
    },
    {
        "id": "malware_l2_q10",
        "field": "Malware Analysis",
        "question": "Which section of a PE file typically contains the malware payload?",
        "options": [".text", ".data", ".rdata", ".rsrc"],
        "correct_answer": ".text",
        "language_required": "N/A"
    }
]

pentest_level2_questions = [
    {
        "id": "pentest_l2_q1",
        "field": "Penetration Testing",
        "question": "Which of the following tools is primarily used for buffer overflow exploits?",
        "options": ["Wireshark", "Metasploit", "Nmap", "John the Ripper"],
        "correct_answer": "Metasploit",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q2",
        "field": "Penetration Testing",
        "question": "What is the main function of the `msfvenom` tool?",
        "options": ["Port scanning", "Payload generation", "SQL fuzzing", "Password cracking"],
        "correct_answer": "Payload generation",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q3",
        "field": "Penetration Testing",
        "question": "Which of the following is NOT a type of penetration test?",
        "options": ["Black box", "Gray box", "White box", "Green box"],
        "correct_answer": "Green box",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q4",
        "field": "Penetration Testing",
        "question": "Which tool is commonly used for subdomain enumeration?",
        "options": ["Hydra", "Dirb", "Sublist3r", "Sqlmap"],
        "correct_answer": "Sublist3r",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q5",
        "field": "Penetration Testing",
        "question": "Which HTTP method can be abused to bypass authentication?",
        "options": ["GET", "POST", "PUT", "OPTIONS"],
        "correct_answer": "OPTIONS",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q6",
        "field": "Penetration Testing",
        "question": "What is the purpose of a reverse shell in penetration testing?",
        "options": ["Scanning ports", "Escalating privileges", "Remote code execution", "Maintaining persistence"],
        "correct_answer": "Remote code execution",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q7",
        "field": "Penetration Testing",
        "question": "Which of these is a web application fuzzing tool?",
        "options": ["Burp Suite Intruder", "Aircrack-ng", "Netcat", "Wireshark"],
        "correct_answer": "Burp Suite Intruder",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q8",
        "field": "Penetration Testing",
        "question": "Which port is commonly scanned for SSH brute-force attempts?",
        "options": ["23", "80", "21", "22"],
        "correct_answer": "22",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q9",
        "field": "Penetration Testing",
        "question": "Which of the following is used to manipulate HTTP requests and responses?",
        "options": ["Snort", "Netcat", "Burp Suite", "Ettercap"],
        "correct_answer": "Burp Suite",
        "language_required": "N/A"
    },
    {
        "id": "pentest_l2_q10",
        "field": "Penetration Testing",
        "question": "What type of attack does the `Responder` tool help simulate?",
        "options": ["DNS spoofing", "SQL injection", "MITM over SMB", "ARP flood"],
        "correct_answer": "MITM over SMB",
        "language_required": "N/A"
    }
]

forensics_level2_questions = [
    {
        "id": "forensics_l2_q1",
        "field": "Digital Forensics",
        "question": "Which file system is most commonly used in Windows forensic analysis?",
        "options": ["EXT4", "NTFS", "FAT32", "APFS"],
        "correct_answer": "NTFS",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q2",
        "field": "Digital Forensics",
        "question": "What tool is widely used for memory analysis in forensics?",
        "options": ["Autopsy", "Ghidra", "Volatility", "Sleuth Kit"],
        "correct_answer": "Volatility",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q3",
        "field": "Digital Forensics",
        "question": "Which file contains information about user login activity in Windows?",
        "options": ["system.log", "NTUSER.DAT", "Security.evtx", "hosts"],
        "correct_answer": "Security.evtx",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q4",
        "field": "Digital Forensics",
        "question": "What is slack space in forensic analysis?",
        "options": ["Encrypted disk space", "Unallocated space", "Unused space within a cluster", "Temporary buffer space"],
        "correct_answer": "Unused space within a cluster",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q5",
        "field": "Digital Forensics",
        "question": "Which hashing algorithm is considered most secure for forensic image validation?",
        "options": ["MD5", "SHA1", "SHA256", "CRC32"],
        "correct_answer": "SHA256",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q6",
        "field": "Digital Forensics",
        "question": "Which Windows artifact indicates program execution?",
        "options": ["Prefetch files", "Hosts file", "Pagefile.sys", "Recycle Bin"],
        "correct_answer": "Prefetch files",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q7",
        "field": "Digital Forensics",
        "question": "Which Linux log file records login attempts?",
        "options": ["/var/log/messages", "/var/log/syslog", "/var/log/auth.log", "/etc/shadow"],
        "correct_answer": "/var/log/auth.log",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q8",
        "field": "Digital Forensics",
        "question": "What does the term 'chain of custody' mean in digital forensics?",
        "options": ["Backup chain method", "Timeline of user activity", "Record of evidence handling", "Network trace path"],
        "correct_answer": "Record of evidence handling",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q9",
        "field": "Digital Forensics",
        "question": "What type of file is a memory dump typically saved as?",
        "options": [".log", ".mem", ".iso", ".img"],
        "correct_answer": ".mem",
        "language_required": "N/A"
    },
    {
        "id": "forensics_l2_q10",
        "field": "Digital Forensics",
        "question": "Which tool is known for timeline analysis in digital forensics?",
        "options": ["Volatility", "Autopsy", "Plaso", "Ghidra"],
        "correct_answer": "Plaso",
        "language_required": "N/A"
    }
]

cloud_level2_questions = [
    {
        "id": "cloud_l2_q1",
        "field": "Cloud Security",
        "question": "Which AWS service allows inspection of VPC traffic?",
        "options": ["CloudTrail", "CloudWatch", "VPC Flow Logs", "IAM"],
        "correct_answer": "VPC Flow Logs",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q2",
        "field": "Cloud Security",
        "question": "What does the shared responsibility model in cloud computing imply?",
        "options": ["Vendors manage all security", "Users are fully responsible", "Security is jointly managed", "Only networks are secured"],
        "correct_answer": "Security is jointly managed",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q3",
        "field": "Cloud Security",
        "question": "Which of the following is an identity federation tool in AWS?",
        "options": ["S3", "EC2", "IAM", "Cognito"],
        "correct_answer": "Cognito",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q4",
        "field": "Cloud Security",
        "question": "What is the risk of misconfigured S3 buckets?",
        "options": ["Service crash", "Public data leakage", "IAM error", "DDoS vulnerability"],
        "correct_answer": "Public data leakage",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q5",
        "field": "Cloud Security",
        "question": "Which framework provides cloud-specific security guidelines?",
        "options": ["NIST CSF", "OWASP Top 10", "CSA CCM", "ISO 9001"],
        "correct_answer": "CSA CCM",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q6",
        "field": "Cloud Security",
        "question": "What is a cloud access security broker (CASB)?",
        "options": ["Key management tool", "Monitoring script", "Policy enforcement point", "Cloud firewall"],
        "correct_answer": "Policy enforcement point",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q7",
        "field": "Cloud Security",
        "question": "Which Azure tool is used to manage security alerts?",
        "options": ["Azure Functions", "Security Center", "Key Vault", "Resource Groups"],
        "correct_answer": "Security Center",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q8",
        "field": "Cloud Security",
        "question": "Which cloud deployment model offers the least control to users?",
        "options": ["Private cloud", "Public cloud", "Hybrid cloud", "Community cloud"],
        "correct_answer": "Public cloud",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q9",
        "field": "Cloud Security",
        "question": "What is the primary purpose of IAM in cloud environments?",
        "options": ["Network segmentation", "Traffic monitoring", "User access control", "Data encryption"],
        "correct_answer": "User access control",
        "language_required": "N/A"
    },
    {
        "id": "cloud_l2_q10",
        "field": "Cloud Security",
        "question": "Which cloud model provides full control over OS and network configurations?",
        "options": ["PaaS", "SaaS", "IaaS", "FaaS"],
        "correct_answer": "IaaS",
        "language_required": "N/A"
    }
]

network_level2_questions = [
    {
        "id": "network_l2_q1",
        "field": "Network Security",
        "question": "Which protocol is commonly targeted in ARP spoofing attacks?",
        "options": ["TCP", "UDP", "ICMP", "ARP"],
        "correct_answer": "ARP",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q2",
        "field": "Network Security",
        "question": "What is the primary function of a firewall?",
        "options": ["Encrypt data", "Detect malware", "Control incoming and outgoing traffic", "Scan for open ports"],
        "correct_answer": "Control incoming and outgoing traffic",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q3",
        "field": "Network Security",
        "question": "Which tool is used to analyze network packets?",
        "options": ["Metasploit", "Burp Suite", "Wireshark", "Nikto"],
        "correct_answer": "Wireshark",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q4",
        "field": "Network Security",
        "question": "Which attack involves flooding a system with SYN requests?",
        "options": ["SYN flood", "Ping of death", "Smurf attack", "DNS spoofing"],
        "correct_answer": "SYN flood",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q5",
        "field": "Network Security",
        "question": "What is the function of an Intrusion Detection System (IDS)?",
        "options": ["Encrypt data", "Block IP addresses", "Monitor and detect malicious traffic", "Balance network load"],
        "correct_answer": "Monitor and detect malicious traffic",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q6",
        "field": "Network Security",
        "question": "Which protocol is used to secure communication over the web?",
        "options": ["HTTP", "FTP", "SSL/TLS", "Telnet"],
        "correct_answer": "SSL/TLS",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q7",
        "field": "Network Security",
        "question": "What is port scanning?",
        "options": ["Flooding a server", "Searching open ports on a host", "Encrypting traffic", "Changing DNS settings"],
        "correct_answer": "Searching open ports on a host",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q8",
        "field": "Network Security",
        "question": "What type of firewall inspects both incoming and outgoing packets?",
        "options": ["Packet-filtering", "Application-layer", "Stateful inspection", "Proxy"],
        "correct_answer": "Stateful inspection",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q9",
        "field": "Network Security",
        "question": "Which command is used in Linux to view active network connections?",
        "options": ["netstat", "ping", "traceroute", "nslookup"],
        "correct_answer": "netstat",
        "language_required": "N/A"
    },
    {
        "id": "network_l2_q10",
        "field": "Network Security",
        "question": "Which DNS record type maps a domain name to an IP address?",
        "options": ["MX", "TXT", "A", "CNAME"],
        "correct_answer": "A",
        "language_required": "N/A"
    }
]

vmware_level2_questions = [
    {
        "id": "vmware_l2_q1",
        "field": "VMware Security",
        "question": "What is the purpose of VMware vShield?",
        "options": ["Snapshot management", "Host migration", "Network security and firewalling", "Storage automation"],
        "correct_answer": "Network security and firewalling",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q2",
        "field": "VMware Security",
        "question": "What is VM escape in virtualization security?",
        "options": ["Cloning a VM", "Isolating a VM", "Running malware inside a VM", "Breaking out of VM to access host"],
        "correct_answer": "Breaking out of VM to access host",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q3",
        "field": "VMware Security",
        "question": "Which feature helps in encrypting VM data at rest in vSphere?",
        "options": ["vMotion", "vSAN", "VM Encryption", "Snapshots"],
        "correct_answer": "VM Encryption",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q4",
        "field": "VMware Security",
        "question": "Which VMware feature ensures secure boot of ESXi hosts?",
        "options": ["VMware Tools", "UEFI Secure Boot", "vApp", "NSX Firewall"],
        "correct_answer": "UEFI Secure Boot",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q5",
        "field": "VMware Security",
        "question": "What does the VMware NSX product primarily provide?",
        "options": ["Application testing", "Storage replication", "Network virtualization and security", "Snapshot management"],
        "correct_answer": "Network virtualization and security",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q6",
        "field": "VMware Security",
        "question": "Which of the following helps prevent unauthorized USB access in VMs?",
        "options": ["vSAN", "vShield", "VM Encryption", "Device Control Policy"],
        "correct_answer": "Device Control Policy",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q7",
        "field": "VMware Security",
        "question": "Which type of attack is specific to hypervisors in virtualization?",
        "options": ["VM escape", "DDoS", "ARP spoofing", "Man-in-the-middle"],
        "correct_answer": "VM escape",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q8",
        "field": "VMware Security",
        "question": "What is the purpose of the lockdown mode in ESXi?",
        "options": ["Disable firewall", "Restrict SSH", "Prevent direct host access", "Force reboot"],
        "correct_answer": "Prevent direct host access",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q9",
        "field": "VMware Security",
        "question": "Which protocol is used by vCenter to communicate with ESXi hosts?",
        "options": ["SSH", "SSL", "vSphere API over HTTPS", "SNMP"],
        "correct_answer": "vSphere API over HTTPS",
        "language_required": "N/A"
    },
    {
        "id": "vmware_l2_q10",
        "field": "VMware Security",
        "question": "What does the Content Library in VMware help manage securely?",
        "options": ["VM power states", "Snapshots", "Templates and ISOs", "Storage clusters"],
        "correct_answer": "Templates and ISOs",
        "language_required": "N/A"
    }
]

iot_level2_questions = [
    {
        "id": "iot_l2_q1",
        "field": "IoT Security",
        "question": "Which protocol is commonly used for lightweight IoT communication?",
        "options": ["HTTP", "FTP", "MQTT", "SSH"],
        "correct_answer": "MQTT",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q2",
        "field": "IoT Security",
        "question": "What is a major risk of hardcoded credentials in IoT devices?",
        "options": ["Device overheating", "Battery drain", "Unauthorized remote access", "Bluetooth failure"],
        "correct_answer": "Unauthorized remote access",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q3",
        "field": "IoT Security",
        "question": "Which technique helps prevent replay attacks in IoT networks?",
        "options": ["Static IPs", "Tokenization", "Time-stamping messages", "Base64 encoding"],
        "correct_answer": "Time-stamping messages",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q4",
        "field": "IoT Security",
        "question": "What is the function of an IoT gateway?",
        "options": ["Enhance WiFi signal", "Monitor power usage", "Bridge local devices to the cloud", "Encrypt radio signals"],
        "correct_answer": "Bridge local devices to the cloud",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q5",
        "field": "IoT Security",
        "question": "Which layer is most targeted in IoT device attacks?",
        "options": ["Application", "Perception", "Transport", "Network"],
        "correct_answer": "Perception",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q6",
        "field": "IoT Security",
        "question": "Which IoT protocol is used for constrained networks and devices?",
        "options": ["TCP", "HTTP", "CoAP", "FTP"],
        "correct_answer": "CoAP",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q7",
        "field": "IoT Security",
        "question": "Which type of attack floods the IoT device with traffic to make it unavailable?",
        "options": ["MITM", "Ransomware", "DDoS", "SQL injection"],
        "correct_answer": "DDoS",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q8",
        "field": "IoT Security",
        "question": "What does OTA stand for in IoT security context?",
        "options": ["Over The Air", "Over The Application", "On Time Access", "Only Trusted Access"],
        "correct_answer": "Over The Air",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q9",
        "field": "IoT Security",
        "question": "Which of the following is a secure practice for IoT firmware updates?",
        "options": ["Using public FTP", "Manual USB updates", "OTA with cryptographic signatures", "Sharing updates over email"],
        "correct_answer": "OTA with cryptographic signatures",
        "language_required": "N/A"
    },
    {
        "id": "iot_l2_q10",
        "field": "IoT Security",
        "question": "What is the role of a Trusted Execution Environment (TEE) in IoT?",
        "options": ["Reduce power", "Enable remote reboot", "Isolate secure operations", "Manage cloud keys"],
        "correct_answer": "Isolate secure operations",
        "language_required": "N/A"
    }
]

appsec_level2_questions = [
    {
        "id": "appsec_l2_q1",
        "field": "Application Security",
        "question": "Which type of vulnerability occurs when user input is improperly escaped in HTML?",
        "options": ["SQL Injection", "Buffer Overflow", "XSS", "CSRF"],
        "correct_answer": "XSS",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q2",
        "field": "Application Security",
        "question": "What does the 'A' in the OWASP A03:2021 stand for?",
        "options": ["Access Control", "Authentication Failures", "Authorization Bypass", "Injection"],
        "correct_answer": "Injection",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q3",
        "field": "Application Security",
        "question": "Which header is used to protect against clickjacking attacks?",
        "options": ["Content-Type", "X-Frame-Options", "Cache-Control", "Set-Cookie"],
        "correct_answer": "X-Frame-Options",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q4",
        "field": "Application Security",
        "question": "What is the purpose of a Content Security Policy (CSP)?",
        "options": ["Limit JavaScript execution", "Block IP addresses", "Encrypt sessions", "Prevent XSS attacks"],
        "correct_answer": "Prevent XSS attacks",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q5",
        "field": "Application Security",
        "question": "Which vulnerability involves tricking users into executing unwanted actions while logged in?",
        "options": ["SQL Injection", "XSS", "CSRF", "LFI"],
        "correct_answer": "CSRF",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q6",
        "field": "Application Security",
        "question": "What is the secure way to handle passwords in modern applications?",
        "options": ["Store in plain text", "Base64 encode them", "Use symmetric encryption", "Hash with bcrypt/scrypt"],
        "correct_answer": "Hash with bcrypt/scrypt",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q7",
        "field": "Application Security",
        "question": "Which testing type examines the internal logic of an application?",
        "options": ["Black-box", "Gray-box", "White-box", "Fuzzing"],
        "correct_answer": "White-box",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q8",
        "field": "Application Security",
        "question": "What is the risk of using outdated third-party libraries?",
        "options": ["Increased memory", "UI mismatch", "Known vulnerabilities", "Licensing issues"],
        "correct_answer": "Known vulnerabilities",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q9",
        "field": "Application Security",
        "question": "Which of the following tools is used for dynamic application security testing (DAST)?",
        "options": ["SonarQube", "ZAP", "Nessus", "Bandit"],
        "correct_answer": "ZAP",
        "language_required": "N/A"
    },
    {
        "id": "appsec_l2_q10",
        "field": "Application Security",
        "question": "What does input validation help prevent?",
        "options": ["Broken access control", "Command injection", "Data loss", "Timeout errors"],
        "correct_answer": "Command injection",
        "language_required": "N/A"
    }
]

reverse_engineering_level2_questions = [
    {
        "id": "reveng_l2_q1",
        "field": "Reverse Engineering",
        "question": "Which file format is commonly used for Windows executables?",
        "options": ["ELF", "PE", "Mach-O", "DEX"],
        "correct_answer": "PE",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q2",
        "field": "Reverse Engineering",
        "question": "Which tool provides interactive disassembly and debugging for x86 binaries?",
        "options": ["Netcat", "GDB", "IDA Pro", "Hydra"],
        "correct_answer": "IDA Pro",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q3",
        "field": "Reverse Engineering",
        "question": "Which section of a PE file typically contains imported DLL names?",
        "options": [".text", ".rsrc", ".idata", ".reloc"],
        "correct_answer": ".idata",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q4",
        "field": "Reverse Engineering",
        "question": "What is the primary purpose of using a debugger in reverse engineering?",
        "options": ["Encrypt files", "Edit memory values", "Understand code behavior", "Obfuscate strings"],
        "correct_answer": "Understand code behavior",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q5",
        "field": "Reverse Engineering",
        "question": "Which tool is developed by NSA for reverse engineering purposes?",
        "options": ["Radare2", "OllyDbg", "Ghidra", "Frida"],
        "correct_answer": "Ghidra",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q6",
        "field": "Reverse Engineering",
        "question": "Which CPU architecture is NOT supported by most reverse engineering tools?",
        "options": ["x86", "ARM", "MIPS", "Quantum"],
        "correct_answer": "Quantum",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q7",
        "field": "Reverse Engineering",
        "question": "What does string obfuscation in binaries aim to prevent?",
        "options": ["Large binaries", "User access", "Signature-based detection", "Static analysis"],
        "correct_answer": "Static analysis",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q8",
        "field": "Reverse Engineering",
        "question": "Which instruction typically marks the end of a function in x86 assembly?",
        "options": ["NOP", "JMP", "RET", "CALL"],
        "correct_answer": "RET",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q9",
        "field": "Reverse Engineering",
        "question": "What is the purpose of 'anti-debugging' techniques in software?",
        "options": ["Optimize speed", "Confuse attackers", "Prevent analysis", "Crash the app"],
        "correct_answer": "Prevent analysis",
        "language_required": "N/A"
    },
    {
        "id": "reveng_l2_q10",
        "field": "Reverse Engineering",
        "question": "Which tool is known for mobile app reverse engineering on Android?",
        "options": ["IDA Free", "MobSF", "Nmap", "Metasploit"],
        "correct_answer": "MobSF",
        "language_required": "N/A"
    }
]

cryptography_level2_questions = [
    {
        "id": "crypto_l2_q1",
        "field": "Cryptography",
        "question": "Which cryptographic algorithm is based on the difficulty of factoring large integers?",
        "options": ["AES", "RSA", "SHA-256", "Blowfish"],
        "correct_answer": "RSA",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q2",
        "field": "Cryptography",
        "question": "What is the primary purpose of a cryptographic hash function?",
        "options": ["Encrypt messages", "Compress files", "Verify data integrity", "Provide confidentiality"],
        "correct_answer": "Verify data integrity",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q3",
        "field": "Cryptography",
        "question": "Which of the following is a symmetric key algorithm?",
        "options": ["RSA", "ECC", "DES", "DSA"],
        "correct_answer": "DES",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q4",
        "field": "Cryptography",
        "question": "Which attack involves finding two inputs that produce the same hash?",
        "options": ["Side-channel attack", "Collision attack", "Replay attack", "Padding oracle attack"],
        "correct_answer": "Collision attack",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q5",
        "field": "Cryptography",
        "question": "Which protocol uses asymmetric encryption for key exchange and symmetric encryption for session data?",
        "options": ["TLS", "SSL", "HTTPS", "SSH"],
        "correct_answer": "TLS",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q6",
        "field": "Cryptography",
        "question": "What is a common key size used in AES encryption?",
        "options": ["56-bit", "128-bit", "160-bit", "1024-bit"],
        "correct_answer": "128-bit",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q7",
        "field": "Cryptography",
        "question": "Which cryptographic technique is used in Bitcoin?",
        "options": ["RSA", "Blowfish", "SHA-256", "3DES"],
        "correct_answer": "SHA-256",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q8",
        "field": "Cryptography",
        "question": "Which algorithm is primarily used for digital signatures?",
        "options": ["RSA", "AES", "SHA1", "MD5"],
        "correct_answer": "RSA",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q9",
        "field": "Cryptography",
        "question": "What is elliptic curve cryptography (ECC) known for?",
        "options": ["Large key sizes", "Fast hashing", "High security with smaller keys", "Slow decryption"],
        "correct_answer": "High security with smaller keys",
        "language_required": "N/A"
    },
    {
        "id": "crypto_l2_q10",
        "field": "Cryptography",
        "question": "Which of the following is a stream cipher?",
        "options": ["DES", "AES", "RC4", "Blowfish"],
        "correct_answer": "RC4",
        "language_required": "N/A"
    }
]

user_interests = [
    "Malware Analysis", "Penetration Testing", "Digital Forensics", "Cloud Security",
    "Network Security", "VMware Security", "Web Security", "Reverse Engineering",
    "Scripting / Automation"
]

user_languages = ["Python", "C/C++", "Bash", "JavaScript"]

# Step 3: Filter questions based on interest/ languages
import random
def filter_questions(questions, interests, languages):
    return [
        q for q in questions
        if q["field"] in interests or q.get("language_required") in languages
    ]

# Create a dictionary to group questions by field
questions_by_field = {}
all_questions = malware_level2_questions + pentest_level2_questions + forensics_level2_questions + \
                cloud_level2_questions + network_level2_questions + vmware_level2_questions + \
                iot_level2_questions + appsec_level2_questions + reverse_engineering_level2_questions + \
                cryptography_level2_questions # Combine all question lists

for q in all_questions:
    field = q["field"]
    if field not in questions_by_field:
        questions_by_field[field] = []
    questions_by_field[field].append(q)

# Take all questions from filtered sets
selected_questions = all_questions

# Step 4: Ask questions and store answers
if not selected_questions:
    print("No questions matched your interests and known languages.")
else:
    user_answers = {}
    for question in selected_questions:
        print("\n" + question["question"])
        for i, option in enumerate(question["options"], 1):
            print(f"{i}. {option}")
        # Input validation
        while True:
            try:
                choice = int(input("Your answer (1-4): "))
                if 1 <= choice <= len(question["options"]):
                    user_answers[question["id"]] = question["options"][choice - 1]
                    break
                else:
                    print("Please enter a number between 1 and 4.")
            except ValueError:
                print("Invalid input. Please enter a number.")

# Step 5: Score the quiz
def score_quiz(questions, user_answers):
    score = 0
    field_scores = {}
    for q in questions:
        correct = q["correct_answer"]
        user = user_answers.get(q["id"])
        if user == correct:
            score += 1
            field_scores[q["field"]] = field_scores.get(q["field"], 0) + 1
    return score, field_scores
total_score, field_scores = score_quiz(selected_questions, user_answers)

# Step 6: Recommend a field
def recommend_field(field_scores):
    if not field_scores:
        return "No strong recommendation"
    max_score = max(field_scores.values())
    top_fields = [field for field, score in field_scores.items() if score == max_score]
    return ", ".join(top_fields)

recommended = recommend_field(field_scores)

print("\nYour Total Score: {}/{}".format(total_score, len(selected_questions)))
print("\nField-wise Scores:")
for field, score in field_scores.items():
    print(f" - {field}: {score} correct")

print("\nBased on your answers, we recommend: **{}**".format(recommended))